docs: usage
SocialGouv/e2esdk pull request #64
Opened 2023-04-26 19:30 UTC by revolunet

2023-05-02 08:19 UTC, matmut7 approved these changes

2023-05-02 09:07 UTC, franky47 requested changes
**suggestion**: Minor edits and precisions to be added to distinguish e2esdk-authenticated users from users providing encrypted form data (different auth mechanisms).

2023-05-02 09:07 UTC, franky47 commented on docs/docs/use-cases/forms.md
> +e2esdk provide dedicated features for forms submissions and sharing. The full-stack example demonstrates such a scenario
```suggestion
e2esdk provides dedicated features for form submissions and sharing. The full-stack example demonstrates such a scenario.
```

2023-05-02 09:07 UTC, franky47 commented on docs/docs/use-cases/forms.md
> +- The submitted data can be re-edited by submitter
```suggestion
- The submitted data can be re-edited by the submitter
```

2023-05-02 09:07 UTC, franky47 commented on docs/docs/use-cases/forms.md
> +While your web application is responsible of storing and distributing the encrypted data and files and provide the correct UI to users, the storing and distribution of decryption keys is entirely han
```suggestion
While your web application is responsible for storing and distributing the encrypted data and files and provide the correct UI to users, the storing and distribution of decryption keys is entirely handled by e2esdk itself and only happens client-side.
```

2023-05-02 09:07 UTC, franky47 commented on docs/docs/use-cases/forms.md
> +### Random users can POST encrypted data
```suggestion
### Anonymous users can POST encrypted data
```

**suggestion**: Make it clear that users POSTing data **may or may not** be e2esdk-authenticated users.

2023-05-06 19:08 UTC, revolunet commented
@SocketSecurity ignore core-js@3.29.1
@SocketSecurity ignore core-js-pure@3.29.1

2023-05-06 19:13 UTC, merged